-- 1. 
DROP TABLE TB_CATEGORY;
CREATE TABLE TB_CATEGORY (
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y' CHECK(USE_YN IN('Y', 'N')) 
);

INSERT INTO TB_CATEGORY(NAME) VALUES ('홍길동');
SELECT * FROM TB_CATEGORY;

-- 2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);