DROP TABLE MEMBER;

CREATE TABLE MEMBER (
    ID VARCHAR(100) PRIMARY KEY,
    PASSWORD VARCHAR(150) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL
);

INSERT INTO MEMBER VALUES('asd', 'asd', '지금이', '경기');
COMMIT;

SELECT * FROM MEMBER;

